/**
 * @description Hello World
 */
public class MyMathClass {

    /** 
     * @description Adds two numbers and returns the result.
     * @param num1 The first number.
     * @param num2 The second number.
     * @return The sum of num1 and num2.
     */
    public static Integer addNumbers(Integer num1, Integer num2) {
        return num1 + num2;
    }

    /**
     * @description Multiplies two numbers and returns the result
     * @param num1 The first number.
     * @param num2 The second number.
     * @return The product of num1 and num2.
     */
    public static Integer multiplyNumbers(Integer num1, Integer num2) {
        return num1 * num2;
    }
}