public class SampleClass {

    // Private variables
    private String greeting;

    // Constructor method
    public SampleClass() {
        // Initialize variables in the constructor
        greeting = 'Default Greeting';
    }


    // Method to add two integers
    public Integer addNumbers(Integer a, Integer b) {
        return a + b;
    }

    // Method to add two doubles
    public Double addNumbers(Double a, Double b) {
        return a + b;
    }

    // Static method to display a static message
    public static void staticMethod() {
        System.debug('This is a static method.');
    }
}
